### PR TITLE
Shrink docker image size

### PR DESCRIPTION
**Pull request by rhld16**
By removing the unused npm module `material-design-icons` and moving most python package installation to another stage I managed to shrink the docker image size from ~340MB (127MB compressed) to ~94MB (34MB compressed).

For some reason I just couldn't get the gunicorn binary to copy over to the production image so theoretically it could be even smaller.

### CODE REVIEW

**Comment by rhld16** [comment]
Some issues found I'll reopen once fixed

**Comment by PhiTux** [comment]
Thanks!

**Comment by rhld16** [comment]
No problems found. I was just running an older image xD

**Comment by PhiTux** [comment]
Doesn't work for me sadly!? In the final image the connection is refused.
Looks like gunicorn is not working properly. The vue-client is online but no backend-connection is possible. 

And I did sadly not find a way to copy gunicorn to the production either :/

**Comment by rhld16** [comment]
Ah shoot. That's odd that it worked once but not the other time for me. Any significant logs? I'll try figure it out later, at worst I guess I could try out different wsgi servers

**Comment by PhiTux** [comment]
No significant logs. 
Well, gunicorn was no problem until now... I would be happy to keep it.

**Comment by rhld16** [comment]
After many frustrations I managed to get the Dockerfile to cooperate and it now works with the added bonus of coming in even smaller at 73MB

**Comment by PhiTux** [comment]
Awesome 😃  Thank you very much!

**Pull request merged**
