### PR TITLE
Add image previewing

### PR DESCRIPTION
**Pull request by rhld16**
This feature displays a modal for any image as a preview so you can view the image without downloading it.
All other files download as usual.

### CODE REVIEW

**Comment by PhiTux** [comment]
Thanks very much! It's already merged locally. Will be published with a few other updates within the next days :)

**Comment by PhiTux** [comment]
So your code is successfully merged and I did add/fix two other things. On local development everything is working fine for me. But not within a docker-image. So it will take a few more days probably to fix the problem with docker...

**Comment by rhld16** [comment]
Those changes look great! I noticed two things with the Docker build, my current implementation makes passing the PORT variable mandatory as well as /api calls being redirected to 'localhost:5000'.

**Comment by PhiTux** [comment]
Yes, I did also notice this thing with 'localhost:5000'...

**Comment by PhiTux** [comment]
The problems seem to go back until commit [911e134](https://github.com/PhiTux/DailyTxT/commit/911e134ea738f59e8446d8c741518eea3671f293#diff-948fe603f61dc036b5c596dc09fe3ce3f3d30dc90f024c85f3c82db2ccab679d). When I rebuild this commit without using cache (!! -> docker build --no-cache ...) then I get the same errors. So perpaps all the new multistage-builds where just working because we both were building the recent docker-images with using cache!? Just an idea...

**Comment by rhld16** [comment]
That would make sense since I'm certain that it's a misconfig with the nginx config files. At least we caught this now rather than later at least xp

**Comment by PhiTux** [comment]
No, I think it's not nginx, but gunicorn is not running inside the new multistage docker!

**Comment by rhld16** [comment]
Oh, that's unexpected... I'll try take a further look into it later

**Comment by PhiTux** [comment]
:D Same here

**Comment by PhiTux** [comment]
Okay, perhaps I found the mistake... If that's true, than it was a stupid mistake by me... Let's see

**Comment by PhiTux** [comment]
Was a missing requirement/dependency for python - my bad 
Now, everything should be fine :)

**Comment by rhld16** [comment]
Ah, nice catch! Can confirm the image works on my instance

**Pull request merged**
